### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by sqwit** [dojci/zabbix-2.2.1_webcheck#1]
Hi There I have a Zabbix server 3.4 running on CentOS 7 VM.

I'm getting the fallowing erro when i try the ./configure
./configure --enable-server --with-libcurl ...
configure: WARNING: you should use --build, --host, --target
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
/home/uxr/zabbix-2.2.1/missing: Unknown `--is-lightweight' option
Try `/home/uxr/zabbix-2.2.1/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: Configuring
checking whether make sets $(MAKE)... (cached) yes
checking build system type... Invalid configuration `...': machine `...' not recognized
configure: error: /bin/sh ./config.sub ... failed

Any idea?

Thanks!

**Comment by dojci** [comment]
Hi the patch is only available for Zabbix 2.2.1 and Zabbix 2.2.6 (see repos) and not for Zabbix 3.4. I dont use zabbix anymore and don't have enough time to build and test web check patch with newer version of Zabbix. Please use build in web scenario or search for another extended web check plugin. Sorry
